# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20121221070603) do

  create_table "loans", :force => true do |t|
    t.integer "loan_id"
    t.float   "amount_requested"
    t.float   "amount_funded_by_investors"
    t.float   "interest_rate"
    t.string  "loan_length"
    t.date    "application_date"
    t.date    "application_expiration_date"
    t.date    "issued_date"
    t.string  "credit_grade"
    t.string  "loan_title"
    t.string  "loan_purpose"
    t.text    "loan_description"
    t.float   "monthly_payment"
    t.string  "status"
    t.float   "total_amount_funded"
    t.float   "debt_to_income_ratio"
    t.float   "remaining_principal_funded_by_investors"
    t.float   "payments_to_date_funded_by_investors"
    t.float   "remaining_principal"
    t.float   "payments_to_date"
    t.string  "screen_name"
    t.string  "city"
    t.string  "state"
    t.string  "home_ownership"
    t.float   "monthly_income"
    t.string  "fico_range"
    t.date    "earliest_credit_line"
    t.float   "open_credit_lines"
    t.float   "total_credit_lines"
    t.float   "revolving_credit_balance"
    t.float   "revolving_line_utilization"
    t.float   "inquiries_in_the_last_6_months"
    t.float   "accounts_now_delinquent"
    t.float   "delinquent_amount"
    t.float   "delinquencies_last_2_yrs"
    t.float   "months_since_last_delinquency"
    t.float   "public_records_on_file"
    t.float   "months_since_last_record"
    t.string  "education"
    t.string  "employment_length"
    t.integer "code"
    t.string  "initial_listing_status"
    t.float   "n_amount_requested"
    t.float   "n_amount_funded_by_investors"
    t.float   "n_interest_rate"
    t.float   "n_application_date"
    t.float   "n_monthly_payment"
    t.float   "n_total_amount_funded"
    t.float   "n_debt_to_income_ratio"
    t.float   "n_remaining_principal_funded_by_investors"
    t.float   "n_payments_to_date_funded_by_investors"
    t.float   "n_remaining_principal"
    t.float   "n_payments_to_date"
    t.float   "n_monthly_income"
    t.float   "n_fico_range"
    t.float   "n_earliest_credit_line"
    t.float   "n_open_credit_lines"
    t.float   "n_total_credit_lines"
    t.float   "n_revolving_credit_balance"
    t.float   "n_revolving_line_utilization"
    t.float   "n_inquiries_in_the_last_6_months"
    t.float   "n_accounts_now_delinquent"
    t.float   "n_delinquent_amount"
    t.float   "n_delinquencies_last_2_yrs"
    t.float   "n_months_since_last_delinquency"
    t.float   "n_public_records_on_file"
    t.float   "n_months_since_last_record"
    t.string  "n_education"
    t.float   "n_employment_length"
    t.integer "n_status"
    t.float   "n_loan_length_36"
    t.float   "n_loan_length_60"
    t.float   "n_home_ownership_own"
    t.float   "n_home_ownership_mortgage"
    t.float   "n_home_ownership_rent"
    t.float   "n_credit_grade_a1"
    t.float   "n_credit_grade_a2"
    t.float   "n_credit_grade_a3"
    t.float   "n_credit_grade_a4"
    t.float   "n_credit_grade_a5"
    t.float   "n_credit_grade_b1"
    t.float   "n_credit_grade_b2"
    t.float   "n_credit_grade_b3"
    t.float   "n_credit_grade_b4"
    t.float   "n_credit_grade_b5"
    t.float   "n_credit_grade_c1"
    t.float   "n_credit_grade_c2"
    t.float   "n_credit_grade_c3"
    t.float   "n_credit_grade_c4"
    t.float   "n_credit_grade_c5"
    t.float   "n_credit_grade_d1"
    t.float   "n_credit_grade_d2"
    t.float   "n_credit_grade_d3"
    t.float   "n_credit_grade_d4"
    t.float   "n_credit_grade_d5"
    t.float   "n_credit_grade_e1"
    t.float   "n_credit_grade_e2"
    t.float   "n_credit_grade_e3"
    t.float   "n_credit_grade_e4"
    t.float   "n_credit_grade_e5"
    t.float   "n_credit_grade_f1"
    t.float   "n_credit_grade_f2"
    t.float   "n_credit_grade_f3"
    t.float   "n_credit_grade_f4"
    t.float   "n_credit_grade_f5"
    t.float   "n_credit_grade_g1"
    t.float   "n_credit_grade_g2"
    t.float   "n_credit_grade_g3"
    t.float   "n_credit_grade_g4"
    t.float   "n_credit_grade_g5"
    t.float   "n_loan_purpose_debt_consolidation"
    t.float   "n_loan_purpose_other"
    t.float   "n_loan_purpose_credit_card"
    t.float   "n_loan_purpose_home_improvement"
    t.float   "n_loan_purpose_small_business"
    t.float   "n_loan_purpose_educational"
    t.float   "n_loan_purpose_vacation"
    t.float   "n_loan_purpose_car"
    t.float   "n_loan_purpose_house"
    t.float   "n_loan_purpose_moving"
    t.float   "n_loan_purpose_wedding"
  end

end
