# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20121221070603) do

  create_table "loans", :force => true do |t|
    t.integer "member_id"
    t.float   "loan_amnt"
    t.float   "funded_amnt"
    t.string  "term"
    t.float   "int_rate"
    t.float   "installment"
    t.string  "grade"
    t.string  "sub_grade"
    t.string  "emp_title"
    t.string  "emp_length"
    t.string  "home_ownership"
    t.integer "annual_inc"
    t.boolean "is_inc_v"
    t.date    "accept_d"
    t.date    "exp_d"
    t.date    "list_d"
    t.date    "issue_d"
    t.string  "loan_status"
    t.string  "pymnt_plan"
    t.string  "url"
    t.string  "desc"
    t.string  "purpose"
    t.string  "title"
    t.string  "addr_city"
    t.string  "addr_state"
    t.integer "acc_now_deliq"
    t.integer "acc_open_past_24mths"
    t.integer "bc_open_to_buy"
    t.float   "percent_bc_gt_75"
    t.float   "bc_util"
    t.float   "dti"
    t.integer "deliq_2yrs"
    t.float   "delinq_amnt"
    t.date    "earliest_cr_line"
    t.integer "fico_range_low"
    t.integer "fico_range_high"
    t.integer "inq_last_6mths"
    t.integer "mths_since_last_delinq"
    t.integer "mths_since_last_record"
    t.integer "mths_since_recent_inq"
    t.integer "mths_since_recent_loan_delinq"
    t.integer "mths_since_recent_revol_delinq"
    t.integer "mths_since_recent_bc"
    t.integer "mort_acc"
    t.integer "open_acc"
    t.integer "pub_rec_gt_100"
    t.integer "pub_rec"
    t.integer "total_bal_ex_mort"
    t.integer "revol_bal"
    t.float   "revol_util"
    t.integer "total_bc_limit"
    t.integer "total_acc"
    t.string  "initial_list_status"
    t.float   "out_prncp"
    t.float   "out_prncp_inv"
    t.float   "total_pymnt"
    t.float   "total_pymnt_inv"
    t.float   "total_rec_prncp"
    t.float   "total_rec_int"
    t.float   "total_rec_late_fee"
    t.date    "last_pymnt_d"
    t.float   "last_pymnt_amnt"
    t.date    "next_pymnt_d"
    t.date    "last_credit_pull_d"
    t.integer "last_fico_range_high"
    t.integer "last_fico_range_low"
    t.integer "total_il_high_credit_limit"
    t.integer "mths_since_oldest_il_open"
    t.integer "num_rev_accts"
    t.integer "mths_since_recent_bc_dlq"
    t.integer "pub_rec_bankruptcies"
    t.integer "num_accts_ever_120_pd"
    t.integer "chargeoff_within_12_mths"
    t.integer "collections_12_mths_ex_med"
    t.integer "tax_liens"
    t.integer "mths_since_last_major_derog"
    t.integer "num_sats"
    t.integer "num_tl_op_past_12m"
    t.integer "mo_sin_rcnt_tl"
    t.integer "tot_hi_cred_lim"
    t.integer "tot_cur_bal"
    t.integer "avg_cur_bal"
    t.integer "num_bc_tl"
    t.integer "num_actv_bc_tl"
    t.integer "num_bc_sats"
    t.integer "pct_tl_nvr_dlq"
    t.integer "num_tl_90g_dpd_24m"
    t.integer "num_tl_30dpd"
    t.integer "num_tl_120dpd_2m"
    t.integer "num_il_tl"
    t.integer "mo_sin_old_il_acct"
    t.integer "num_actv_rev_tl"
    t.integer "mo_sin_old_rev_tl_op"
    t.integer "mo_sin_rcnt_rev_tl_op"
    t.integer "total_rev_hi_lim"
    t.integer "num_rev_tl_bal_gt_0"
    t.integer "num_op_rev_tl"
    t.integer "tot_coll_amt"
    t.integer "policy_code"
    t.float   "n_loan_length_36"
    t.float   "n_loan_length_60"
    t.float   "n_home_ownership_own"
    t.float   "n_home_ownership_mortgage"
    t.float   "n_home_ownership_rent"
    t.float   "n_credit_grade_a1"
    t.float   "n_credit_grade_a2"
    t.float   "n_credit_grade_a3"
    t.float   "n_credit_grade_a4"
    t.float   "n_credit_grade_a5"
    t.float   "n_credit_grade_b1"
    t.float   "n_credit_grade_b2"
    t.float   "n_credit_grade_b3"
    t.float   "n_credit_grade_b4"
    t.float   "n_credit_grade_b5"
    t.float   "n_credit_grade_c1"
    t.float   "n_credit_grade_c2"
    t.float   "n_credit_grade_c3"
    t.float   "n_credit_grade_c4"
    t.float   "n_credit_grade_c5"
    t.float   "n_credit_grade_d1"
    t.float   "n_credit_grade_d2"
    t.float   "n_credit_grade_d3"
    t.float   "n_credit_grade_d4"
    t.float   "n_credit_grade_d5"
    t.float   "n_credit_grade_e1"
    t.float   "n_credit_grade_e2"
    t.float   "n_credit_grade_e3"
    t.float   "n_credit_grade_e4"
    t.float   "n_credit_grade_e5"
    t.float   "n_credit_grade_f1"
    t.float   "n_credit_grade_f2"
    t.float   "n_credit_grade_f3"
    t.float   "n_credit_grade_f4"
    t.float   "n_credit_grade_f5"
    t.float   "n_credit_grade_g1"
    t.float   "n_credit_grade_g2"
    t.float   "n_credit_grade_g3"
    t.float   "n_credit_grade_g4"
    t.float   "n_credit_grade_g5"
    t.float   "n_loan_purpose_debt_consolidation"
    t.float   "n_loan_purpose_other"
    t.float   "n_loan_purpose_credit_card"
    t.float   "n_loan_purpose_home_improvement"
    t.float   "n_loan_purpose_small_business"
    t.float   "n_loan_purpose_educational"
    t.float   "n_loan_purpose_vacation"
    t.float   "n_loan_purpose_car"
    t.float   "n_loan_purpose_house"
    t.float   "n_loan_purpose_moving"
    t.float   "n_loan_purpose_wedding"
  end

end
